### ISSUE TITLE
Given a query, can we download a list of files that need to be moved by some tool?

### ISSUE THREAD

**Issue by bnlawrence** [NCAS-CMS/cfstore#114]
Can we have that as a manifest, rather than a text file?

**Comment by bnlawrence** [comment]
(Can we have an example of what we have right now)

**Comment by georgeoobrienNCAS** [comment]
![image](https://github.com/NCAS-CMS/cfstore/assets/93651037/820ad25c-6bfd-45a3-9c60-690fbd80b930)
![image](https://github.com/NCAS-CMS/cfstore/assets/93651037/fe811ade-2228-4d55-9219-677190c2320e)

Output is generated by:
`filenames = (f.path + "/" + f.name + "<br>" for f in files if f.name.endswith(".nc"))`
where files is a list of Django File models.
path, name and locations are inbuilt and easy to access in these models.
As is (if necessary) format, locations size and replica files

Needs some work with the exact output. 

Latest available in:
https://github.com/NCAS-CMS/cfstore/pull/124
