### ISSUE TITLE
Get people's email addresses out of data 

### ISSUE THREAD

**Issue by bnlawrence** [NCAS-CMS/cfstore#115]
No netcdf file should ever have a human target email address, as humans move on. We need addresses which can be redirected like "canari@ncas.ac.uk" which redirects (for now) to Reinhard. Talk to Reinhard and Grenville and fix going forward.

**Comment by bnlawrence** [comment]
For the data we have, we don't want to rewrite, so for now we need some written GDPR permission.

**Comment by bnlawrence** [comment]
Grenville thinks there should not be any? it should be institutional? What attributes and data are generating these?

**Comment by bnlawrence** [comment]
Can you please provide Grenville a list of the files.
Meanwhile, we can probably fix it in the CFA file, before we ingest it?

**Comment by georgeoobrienNCAS** [comment]
Spoke with Grenville here "ah no it's old test junk that's been dumped on tape u-cn134-1fpf  is not a production suite"
So we shouldn't have emails addresses in main canari files. Will keep eye on it though.

**Comment by davidhassell** [comment]
Sounds like there's nothing to see here, but for the record we can definitely delete unwanted properties from the fields, at any stage:
```python
for f in fields:
    f.del_properties(list_of_unwanted_properties)
```
