### ISSUE TITLE
Build test set for "minimal" b-metadata ingestion

### ISSUE THREAD

**Issue by georgeoobrienNCAS** [NCAS-CMS/cfstore#85]
Test:
ssh connection
moving and removing a script
running the script offline
printing script results
everything in a row

**Comment by bnlawrence** [comment]
Either in this, or another test, we need to take the json, upload it to the database and consider the following:
 - were all the files in the target folder(s) ingested (count files in target, and files in the database)?
 - was all the expected b-metadata harvested, can we query our database and get back the files given common b-metadata?
 - can we retrieve the b-metadata from one file and confirm it is all there?
 - is there a deduplication of common metadata across files?
